version: '3'

services:
  proxy:
    image: traefik
    command: --web --web.address=":${ADMIN_PORT}" --entrypoints="Name:http Address::${HTTP_ENTRYPOINT_PORT}" --docker --docker.domain="${DOCKER_DOMAIN}" --logLevel=DEBUG
    networks:
      - default
    ports:
      - "${HTTP_ENTRYPOINT_PORT}:${HTTP_ENTRYPOINT_PORT}"
      - "${ADMIN_PORT}:${ADMIN_PORT}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml

networks:
  default:
    driver: bridge
