version: '2'

services:
  proxy:
    image: traefik
    # command: --web --docker --docker.domain=docker.localhost --entrypoints="Name:http Address::81" --defaultentrypoints="http" --logLevel=DEBUG
    networks:
      - default
    ports:
      - "81:81"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml

networks:
  default:
    driver: bridge
